version: "3.1"
services:
  trello_mysql:
    image: mysql
    container_name: trello_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: trello
    ports:
      - "3307:3306"

  trello_adminer:
    image: adminer
    container_name: trello_adminer
    restart: always
    ports:
      - 8080:8080
